language: java
sudo: false
install: true
jdk:
- oraclejdk8
script:
- "./bin/travis.sh"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  sonarqube:
    token:
      secure: h5I6eV9+VT8aeZEld/BI9otWMLvxnsGjK4XpTl/noHw6TBXdinUqgQ2RfFgrvbk3rtgkNgP61oGGDU3wzWqJrpKc2/hMjiYG3r4VsNqsDsFh67X+WqCqHfvG+DPNUHeaAYP6kdA1gVNG7TZuPscYPl4Oacxm8Uxchbe8rPZ/8gItIMRg7pOeNkWDUDj5dpUCNz1JukjvPCpT8C87jA5PNei5iwBIf6y6U9d35DKd3j0bFPdK3pWilwrs4uc3DYSQnI+Ci9baoIoK3f7DLY22cJS6S+MvzMO/zfyaxSzi8egeroJojyg6lrNZXzRAIa6bal8wFkhjy8uQw+LJMncvCp+XFDZHNAZ0+x5AgqHhLDvwln3lMtsInmjmKkPi+JzmfdESctobacP5h6LGEycv9VmokkBbQa9zAELVq92V+5biNjb/yDaS25DmRoyrbf9X++Yvyzz4nn4UzKhiovVSxyRlrsg9zocO3BzTSvWFOjGNuu5BkDeyEUz8ncXXQmHTLA7LD/cX0WJlZKm3VbKQLzX2B8zW7XlatTvlhztkOVLvxk/pZzZr9N4RXBVgRA7OA+74JStHjCN7zOlRY4pY6PpcTk7hZeMfjRf/S9MXkrv9oiFlJDVsqAbJK6UdfTAZ3IFWCR9CXjBG5zd+jUOZOZvKd5rVIsKx7BOPocX5ZcA=
    github_token:
      secure: e4G+U+/bqlQ5se2mW4D+dHxPTNhyOFCGYXP6Zqq8cobz+srbzgnoGKAR0Vhbrh9PFDqKlUh5tnrK1dL8QcPwYW6/5hctoApXiWEwB7yzP0vJV1PYl9ihiSTjk//0LBjY44jChPsFQ/eTliglVvpApi0YHIp78nxt8byTlHDtG9dAmhUHewHG4LL2yRp9WfqXyzKbB4Iq52zMvghEr11N/C1g49X4jhdLGuF3vZUojwaO3y4zdGoZxkbWMbxe/JScMlYp+SzBm3X3xnA5fO94v0DpWaGXli5qBdGxi4W5l5xh6yet3tJrzlC4EHgN2O43krg2wTAtgJ1S2Ti56bgMJ7JV8UEEOOHemTEfrirQOIY4dOa/LY/5yh/gsLdtgAOdshj9DW4Gnry7GcQhXsw8nQkBmCM5oOs3y/7JOgohehbymeu1nshv5vdCG16Tb1dXXSfVLII8hWLg+MX/MBeuZ4VaVQUIvTmK+Xfxm+v6Wo103z68Vydij1o/kQLTRMEYbkRlEqaeICZhjaVMXM98KXD6t2YBXNC+t73Z/kdNcYlkFOeBnYhVnOrurxdtpx7TKUaq5wjfE46jFaK//P1JKaPsNxBPObhFg8ek07ySAq/0C6/K5tEVCFZNDavnYHnFdRTDHG5T2wy3jNEQdiJMn1slg3kIkYH0HPeHizcbPwA=
